# 作業目標:

    使用CIFAR100, 數據集變大的影響
    
    
# 作業重點:¶

   了解 CIFAR100 跟 CIFAR10 數據及差異


In [7]:
import numpy
from keras.datasets import cifar100
import numpy as np
np.random.seed(100)

C:\Anaconda3\envs\keras35\lib\importlib\_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 88 from C header, got 96 from PyObject
  return f(*args, **kwds)
Using TensorFlow backend.


# 資料準備

In [24]:
AA = cifar100.load_data()

In [15]:
(x_img_train,y_label_train),\
(x_img_test,y_label_test) = cifar100.load_data(label_mode='fine')

In [16]:
print('train:',len(x_img_train))
print('test :',len(x_img_test))

train: 50000
test : 10000


In [17]:
# 查詢檔案維度資訊
x_img_train.shape

(50000, 32, 32, 3)

In [18]:
# 查詢檔案維度資訊
y_label_train.shape

(50000, 1)

In [19]:
# 查詢檔案維度資訊
x_img_test.shape

(10000, 32, 32, 3)

In [20]:
# 查詢檔案維度資訊
y_label_test.shape

(10000, 1)

In [ ]:
#針對物件圖像數據集的類別編列成字典
## 有太多分類 100 個，沒辦法一一輸入

label_dict={0:"aquatic mammals",1:"fish",2:"flowers",3:"food containers",4:"fruit and vegetables",
            5:"household electrical devices",6:"household furniture",7:"insects",8:"large carnivores",9:"large man-made outdoor things",
           }

In [48]:
#導入影像列印模組
import matplotlib.pyplot as plt

#宣告一個影像標記的函數
def plot_images_labels_prediction(images,labels,prediction,
                                  idx,num=10):
    fig = plt.gcf()  ## 得到當前的數字 figure
    fig.set_size_inches(12, 14)
    if num>25: num=25 
    for i in range(0, num):
        ax=plt.subplot(5,5, 1+i)  ## 5行5列 第幾張圖
        ax.imshow(images[idx],cmap='binary')    ##   matplotlib.pyplot.imshow(X, cmap=None)
                                                ##  X: 要绘制的图像或数组。
                                                ### cmap: 颜色图谱（colormap), 默认绘制为RGB(A)颜色空间。
                
        title=str(i)+','+label_dict[labels[i][0]]  ## 從字典裡找出分類，依據labels[i][0]對應的數字
        print(title)
        if len(prediction)>0:
            title+='=>'+label_dict[prediction[i]]
            print('333'+title)

            
        ax.set_title(title,fontsize=10) 
        ax.set_xticks([]);ax.set_yticks([])        
        idx+=1 
    plt.show()

In [ ]:
#針對不同的影像作標記

plot_images_labels_prediction(x_img_train,y_label_train,[],0)

In [ ]:
print('x_img_test:',x_img_test.shape)
print('y_label_test :',y_label_test.shape)

# Image normalize 

In [27]:
x_img_train[0][0][0]

array([255, 255, 255], dtype=uint8)

In [28]:
x_img_train_normalize = x_img_train.astype('float32')/255.0
x_img_test_normalize = x_img_test.astype('float32')/255.0

In [32]:
x_img_train_normalize[0][0][0]

array([1., 1., 1.], dtype=float32)

# 轉換label 為OneHot Encoding

In [33]:
y_label_train.shape

(50000, 1)

In [40]:
y_label_train[:5]

array([[19],
       [29],
       [ 0],
       [11],
       [ 1]])

In [41]:
from keras.utils import np_utils

In [43]:
y_label_train_OneHot = np_utils.to_categorical(y_label_train)
y_label_test_Onehot = np_utils.to_categorical(y_label_test)

In [44]:
y_label_train_OneHot.shape

(50000, 100)

In [47]:
y_label_train_OneHot[:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.